# 2.1 数据操作

mxnet 与 numpy 兼容设置：

In [1]:
from mxnet import np, npx

npx.set_np()

常用数据操作

In [ ]:
# np.arrange 创建 0,1,2,3,4,....,10,11
x = np.arange(12)
print(f"x data: {x}")
print(f"x shape: {x.shape}")
print(f"x size: {x.size}")
X = x.reshape((3, 4))
print(f"x reshaped to X: {X}")

x data: [ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]
x shape: (12,)
x size: 12
x reshaped to X: [[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]


In [15]:
print(np.zeros((2,3,4)))
print(np.ones((2,3,4)))

# 创建一个形状为 (3,4) 的张量
# 其中的每个元素都从均值为 0、标准差为 1 的标准高斯分布（正态分布）中随机采样
print(np.random.normal(0,1,size=(3,4)))

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
[[ 1.1630787   2.2122064   0.4838046   0.7740038 ]
 [ 0.29956347  1.0434403   0.15302546  1.1839255 ]
 [-1.1688148   1.8917114   1.5580711  -1.2347414 ]]


In [16]:
np.array([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

array([[2., 1., 4., 3.],
       [1., 2., 3., 4.],
       [4., 3., 2., 1.]])

In [4]:
X = np.arange(12).reshape(3,4)
X[0:2, :] = 12
X

array([[12., 12., 12., 12.],
       [12., 12., 12., 12.],
       [ 8.,  9., 10., 11.]])

练习题：X > Y / X < Y 判断打印

In [8]:
X = np.arange(12).reshape(3, 4)
Y = np.array([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
print(X)
print(Y)

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
[[2. 1. 4. 3.]
 [1. 2. 3. 4.]
 [4. 3. 2. 1.]]


In [10]:
print(X == Y)
print(X < Y)
print(X > Y)

[[False  True False  True]
 [False False False False]
 [False False False False]]
[[ True False  True False]
 [False False False False]
 [False False False False]]
[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]


练习题：广播机制测试