# 2.3 线性代数

## 范数 Norm

### L1 范数（曼哈顿范数）

计算所有元素的绝对值之和。

$$
|| x ||_1 = \sum^{n}_{i=1} | x_i |
$$

### L2 范数（欧几里得范数）

计算距离

$$
|| x ||_2 = \sqrt{\sum^{n}_{i=1} x^2_i}
$$

### Lp 范数（一般形式）

$$
|| x ||_p = (\sum^n_{i=1} | x_i |^p)^{1/p}
$$

* L1 和 L2 是 Lp 范数的特例
* 通过调节 p 来控制范数行为

## 练习题



练习题 1：证明一个矩阵 $A$ 的转置是 $A$，即 $(A^T)^T = A$

In [2]:
import numpy as np
A = np.arange(12).reshape(3, 4)
A.T.T == A

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

练习题 2：给出两个矩阵 $A$ 和 $B$，证明 “它们转置的和” 等于 “它们和的转置”，即 $A^T + B^T = (A+B)^T$。

In [3]:
A = np.arange(12).reshape(3,4)
B = np.arange(12,24).reshape(3,4)
(A.T + B.T) == (A+B).T

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

练习题 3：给定任意方阵 $A$，$A+A^T$ 总是对称的吗？为什么？

In [4]:
A = np.arange(16).reshape(4,4)
(A + A.T) == (A + A.T).T

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

练习题 4：本节中定义了形状的 (2,3,4) 的张量 X，len(X) 的输出结果是什么？

In [5]:
A = np.arange(24).reshape(2,3,4)
len(A)

2

练习题 5：对于任意形状的张量 X，len(X) 是否总是对应于 X 特定轴的长度？这个轴是什么？

len(X) 只能返回第一维的大小，即第 0 轴。

In [6]:
A.shape

(2, 3, 4)

练习题 6：运行 A/A.sum(axis=1)，看看会发生什么。请分析一下原因？

ValueError: operands could not be broadcast together with shapes (2,3,4) (2,4) 

两个张量纬度不同，不能进行逐个元素的除法运算。

In [7]:
A / A.sum(axis=1)

ValueError: operands could not be broadcast together with shapes (2,3,4) (2,4) 

练习题 7：考虑一个具有形状 (2,3,4) 的张量，在轴 0、1、2 上的求和输出是什么形状？

In [12]:
A = np.arange(24).reshape(2,3,4)
print(f"Axis 0 Sum: {A.sum(axis=0).shape}")
print(f"Axis 1 Sum: {A.sum(axis=1).shape}")
print(f"Axis 2 Sum: {A.sum(axis=2).shape}")

Axis 0 Sum: (3, 4)
Axis 1 Sum: (2, 4)
Axis 2 Sum: (2, 3)


练习题 8：为 linalg.norm 函数提供 3 个或更多轴的张量，并观察其输出。对于任意形状的张量这个函数计算得到什么？

对应得到的是 L2 范数的计算结果。

In [ ]:
np.linalg.norm(A)

65.75712889109438